#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-cpuguy83-go-md2man
Version  : 1.0.6
Release  : 10
URL      : https://github.com/cpuguy83/go-md2man/archive/v1.0.6.tar.gz
Source0  : https://github.com/cpuguy83/go-md2man/archive/v1.0.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause MIT
Requires: golang-github-cpuguy83-go-md2man-bin
BuildRequires : go
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Rework-directory-structure-to-build-from-tar.patch

%description
go-md2man
=========
** Work in Progress **
This still needs a lot of help to be complete, or even usable!

%package bin
Summary: bin components for the golang-github-cpuguy83-go-md2man package.
Group: Binaries

%description bin
bin components for the golang-github-cpuguy83-go-md2man package.


%prep
%setup -q -n go-md2man-1.0.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export GOPATH="$PWD"
go build

%install
rm -rf %{buildroot}

## make_install_append content
install -d -m0755 %{buildroot}/usr/bin
install -m0755 go-md2man-1.0.6 %{buildroot}/usr/bin/go-md2man
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/go-md2man
