#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-cpuguy83-go-md2man
Version  : 1.0.6
Release  : 8
URL      : https://github.com/cpuguy83/go-md2man/archive/v1.0.6.tar.gz
Source0  : https://github.com/cpuguy83/go-md2man/archive/v1.0.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause MIT

%description
go-md2man
=========
** Work in Progress **
This still needs a lot of help to be complete, or even usable!

%prep
%setup -q -n go-md2man-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C

%install
gopath="/usr/lib/golang-dist"
library_path="github.com/cpuguy83/go-md2man"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done


%files
%defattr(-,root,root,-)
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/md2man.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/md2man/md2man.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/md2man/roff.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/block.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/html.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/inline.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/latex.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/markdown.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/smartypants.go
/usr/lib/golang-dist/src/github.com/cpuguy83/go-md2man/vendor/github.com/shurcooL/sanitized_anchor_name/main.go
